### ISSUE TITLE
Error calling dumps() on a slice

### ISSUE THREAD

**Issue by remram44** [Psycojoker/redbaron#66]
`script.dumps()` works fine, but `script[1:3].dumps()` seems to be missing some line endings...

[Example notebook](http://nbviewer.ipython.org/gist/remram44/d34eb7a935ba52928088)

**Comment by Psycojoker** [comment]
Hello,

Actually, what you are facing is the "very confusing in this case but excepted" behavior, or said in another way "oh, I've never actually though about using .dumps() in this situation but it's normal that it's working this way".

To explain, right now you are working on a [proxy list](https://redbaron.readthedocs.org/en/latest/proxy_list.html), a list where you do see the formatting separator, here <code>\n</code>, you have to use the <code>.node_list</code> to access the unproxified list. And basically what <code>.dumps()</code> is doing is more or less <code>"".join(map(lambda x: x.dumps(), self)</code>, so no <code>\n</code> node ends up in the generated dumps.

Except, and you it gets funny (I hope that you are still following my explanation :p), in its current behavior, nodes that have an indented body grab every <code>\n</code> after their body, this is why you have a <code>\n</code> after your <code>if</code> node here. Without node with indented body, the behavior is more consistent:

```python
In [4]: RedBaron("a\nb\nc\nd\n")[0:4].dumps()
Out[4]: 'abcd'
```

So, to conclude:

* the "node with an indented body grabs <code>\n</code> will be modified by this PR https://github.com/Psycojoker/redbaron/pull/63 that *might* make the behavior more consistent
* while this behavior is the "expected" one, it is actually quite a big usability bug, I need to think about it, but right now my intuitive solution would be to modify <code>"".join(map(lambda x: x.dumps(), self)</code> to <code>expected_separator_of_this_proxylist.join(map(lambda x: x.dumps(), self)</code>. I'm not jumping on that strategy immediately because edge cases are high chances of being present and I need to investigate. 

Thanks for reporting and thanks for taking the time to provide an example notebook :)

**Comment by remram44** [comment]
I think I get what you mean, but can't find a workaround; using `.node_list.data` doesn't give me a coherent list I can join() on either... or does it?

**Comment by remram44** [comment]
Wait no, I get it: I should be slicing on the `.node_list` in the first place. I pushed [this](https://github.com/VisTrails/VisTrails/commit/c7d4691643eb1ea8c193913e0321619cce9d7d6b) which is probably what you meant. Thanks!

**Comment by Psycojoker** [comment]
Well, I don't know your code, but it looks like it is yes :)
